name: SkBriggy
main: com.shanebeestudios.briggy.SkBriggy
version: '$version'
api-version: '1.20.0'
author: 'ShaneBee'
website: 'https://github.com/ShaneBeee/SkBriggy'
description: 'A Skript addon for Brigadier commands'
dependencies:
  server:
    Skript:
      load: BEFORE
      required: true
    SkBee:
      load: BEFORE
      required: false
