
brig command tree /brigtest:
	int arg "int":
		string arg "s":
			trigger:
				set {brig_test::%{_s}%} to {_int}
		trigger:
			set {brig_test::just_int} to {_int}

test "SkBriggy - Command Tree":
	stop
	# This test is currently broken due to CommandAPI change
	# The command cannot be executed in console right away
	# Once the commands finish loading, the datapacks need to reload before they can be used
	# Unfortunately CommandAPI no longer has an option to disable this.
	delete {brig_test::*}
	set {_i} to random integer between 1 and 100
	set {_s} to random uuid
	set {_c} to run command "/brigtest %{_i}% %{_s}%"
	assert {_c} = true with "The command should have fun"
	assert {brig_test::%{_s}%} = {_i} with "The command (with 2 args) should have run"
	delete {_i} and {_c}

	set {_i} to random integer between 1 and 100
	set {_c} to run command "/brigtest %{_i}%"
	assert {_c} = true with "The command should have fun"
	assert {brig_test::just_int} = {_i} with "The command (with 1 arg) should have run"
	delete {_i} and {_c}

	set {_c} to run command "/nothingcommand"
	assert {_c} = false with "The command should have failed"

	delete {brig_test::*}
